[project]
name = "dash"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pandas>=2.3.1",
    "plotly>=6.2.0",
]

[dependency-groups]
dev = [
    "dash",
]

[tool.uv.sources]
dash = { workspace = true }
